# Generated by Django 5.0 on 2023-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
