# Generated by Django 5.0 on 2023-12-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_alter_index_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='text',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
